class canvasInstances {
  static loader(hardcodedId, dynamicId){
    //Every canvas will have a internal hard-coded id
    //and a dynamic id generated by Canvas element
    //the dynamic id will be storaged in a object of IDS
    if(window.canvasInstances == undefined)
      window.canvasInstances = new Object();
    
    if(window.canvasInstances[hardcodedId] == undefined)
      Object.assign(window.canvasInstances,{[hardcodedId]:null});
    
    window.canvasInstances[hardcodedId] = dynamicId;
    console.log(window.canvasInstances);
  }
  static checker(hardcodedId, dynamicId){ 
    // console.log(window.canvasInstances[hardcodedId]);
    const res = window.canvasInstances[hardcodedId] == undefined? false : window.canvasInstances[hardcodedId] == dynamicId;
    // console.log(res) 
    if(!res)console.warn("refusing engine start from prebult canvas")
    return res;
  } 
}
export{canvasInstances}