class canvasInstances {
  static loader(hardcodedId, dynamicId){
    //Every canvas will have a internal hard-coded id
    //and a dynamic id generated by Canvas element
    //the dynamic id will be storaged in a object of IDS
    if(window.canvasInstances == undefined)
      window.canvasInstances = new Object();
    
    if(window.canvasInstances[hardcodedId] == undefined)
      Object.assign(window.canvasInstances,{[hardcodedId]:null});
    
    window.canvasInstances[hardcodedId] = dynamicId;

    window.finalWarn = 0;
    console.log(window.canvasInstances);
  }
  static checker(hardcodedId, dynamicId){ //REMOVED THE RECALLING TO DRAW CHECKING
    var res = window.canvasInstances[hardcodedId] == undefined? false : window.canvasInstances[hardcodedId] == dynamicId;
    if("registrant" in window){
      if(window.registrant.reduce((partialSum, a) => partialSum + a, 0) >= 1000){
        // console.log("ticks per second: ", window.registrant.length);
        window.registrant = [];
      }
    }else{window.registrant = [];}
    if("delting" in window){
      const delta = performance.now() - window.delting;
      // console.log(dynamicId,res,delta);
      window.registrant.push(delta);
    }
    window.delting = performance.now();
    return res;
  }    
}
export{canvasInstances}