// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Request(arg1) {
  return window['go']['main']['App']['Request'](arg1);
}

export function RequestFile(arg1) {
  return window['go']['main']['App']['RequestFile'](arg1);
}

export function RequestFileWithMime(arg1) {
  return window['go']['main']['App']['RequestFileWithMime'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
