// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Request(arg1:Record<string, string>):Promise<any>;

export function RequestFile(arg1:string):Promise<string>;

export function RequestFileWithMime(arg1:string):Promise<string>;

export function ToggleFullscreen():Promise<void>;
